apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-v.fullname" . }}
  labels: {{- include "agent-v.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "agent-v.selector" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
